cmake -DENABLE_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DENABLE_CLDNN=ON -DENABLE_INTEL_GNA=OFF -DENABLE_INTEL_MYRIAD=OFF -DENABLE_INTEL_MYRIAD_COMMON=OFF -DENABLE_DEBUG_CAPS=ON -DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=gold -DENABLE_OV_ONNX_FRONTEND=OFF -DENABLE_OV_TF_FRONTEND=OFF -DENABLE_OV_PADDLE_FRONTEND=OFF -GNinja ..

